name: Build Kernel Images

on:
  push:
    branches: [ "main", "workflow" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kernel: [bazzite, cachy, ubuntu, xanmod, surface]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Kernel Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./kernels/${{ matrix.kernel }}-kernel.dockerfile
          tags: kerneless:${{ matrix.kernel }}
          load: true 
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: List Images
        run: docker images | grep kerneless